### PR TITLE
Windows install

### PR DESCRIPTION
**Pull request by JenniferBuehler**
I've added the instructions I wrote down while compiling on Windows. Maybe the best approach is if somebody else tries this again before merging?
It may also be possible to simplify the documentation, which should be done along a second try of the installation, to verify the simplifications.

### CODE REVIEW

**Comment by jvarley** [comment]
The file dlfcn-win32.h and dlfcn-win32.cpp are not mentioned in the CMakeLists.txt. Here is how they were used with the old .pro file.  Can we just get rid of these two files, or are they needed in some form for use on windows?

jvarley@skye:~/graspit_breakup$ grep -ir dlfcn-win32 .
./src/dlfcn-win32.cpp: * dlfcn-win32
./src/dlfcn-win32.cpp:#include "dlfcn-win32.h"
./src/plugin.cpp:#include "dlfcn-win32.h"
./graspit-lib-WINDOWS.pro:INCLUDES += include/dlfcn-win32.h
./graspit-lib-WINDOWS.pro:SOURCES += src/dlfcn-win32.cpp
./doc/hyperlatex/installation_windows.tex:Using Graspit! in Windows , we need to get a copy of dlfcn for plugin.  One version is from Google code.  You can download it from here: \xlink{http://code.google.com/p/dlfcn-win32}{http://code.google.com/p/dlfcn-win32}.
./graspit-core.pro:     SOURCES += src/dlfcn-win32.cpp
./graspit-core.pro:     HEADERS += include/dlfcn-win32.h
./include/dlfcn-win32.h: * dlfcn-win32

**Comment by JenniferBuehler** [comment]
Yes I don't think it's needed, grep shows no use of it. Shall I push a change with the dlfcn-win32.h/.cpp removed?

**Comment by jvarley** [comment]
@JenniferBuehler 

I know it has been awhile, but any chance you could help take your README and update:
https://github.com/graspit-simulator/graspit-simulator.github.io_src

So that it will be part of the docs here:
http://graspit-simulator.github.io/build/html/installation_windows.html

**Comment by JenniferBuehler** [comment]
Hi Jake,

no problem. Just to make sure I get this right: You'd like me to edit both documentation links directly with the contents of my README?

Cheers
Jenny

**Comment by jvarley** [comment]
https://github.com/graspit-simulator/graspit-simulator.github.io_src
  is the source for the docs shown here:
http://graspit-simulator.github.io/build/html/installation_windows.html

So if you could make a pr for an updated version of:
https://github.com/graspit-simulator/graspit-simulator.github.io_src/blob/master/source/installation_windows.rst

with the content of your README, it will then appear at:
http://graspit-simulator.github.io/build/html/installation_windows.html

**Comment by JenniferBuehler** [comment]
Ok, will do this as soon as possible, probably the weekend.

Jenny

**Comment by jvarley** [comment]
This has been added to the documentation in the user manual.

**Pull request closed without merging**
