### PR TITLE
Added parallel gripper from Rethink Robotic's Baxter robot.

### PR DESCRIPTION
**Pull request by JSR694**
Based on [Rethink's electric gripper URDF](https://github.com/RethinkRobotics/baxter_common/tree/master/rethink_ee_description).  Converted to a Graspit model with Jennifer Buehler's urdf2graspit, with some manual tweaks.

This model does not currently work well with a simple SimAnn planner + contactAndPotential search energy.  I am currently tweaking the planner settings to find what works best.  Additionally, a simplified model (based on primitives) may be released in the future to improve performance.

### CODE REVIEW

**Comment by jvarley** [comment]
Can you add the following to the top of all the .iv files:

Copyright (c) 2013-2015, Rethink Robotics
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. Neither the name of the Rethink Robotics nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.

**Comment by jvarley** [comment]
@mateiciocarlie 

As long as that license is placed on the mesh files, is this PR ok with you?

**Comment by jvarley** [comment]
im13

**Comment by mateiciocarlie** [comment]
Looks good to me!

**Comment by jvarley** [comment]
Can you switch the tops of the iv files to the following.  It needs to have the Inventor line as the very first line in the file, then you can have the license, or else graspit fails to parse the file.  Then we should be good to go.:

#Inventor V2.1 ascii

# Copyright (c) 2013-2015, Rethink Robotics
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#     Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
#     Neither the name of the Rethink Robotics nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

**Comment by JenniferBuehler** [comment]
Thanks for adding this!

One thing to maybe adjust in future would be to keep the baxter.xml as the output from urdf2graspit and keep manual adjustments in the eigen.xml, so that the mirroring behaviour of the grippers can be considered in the planning (the identity grasps don't reflect what's in the URDF, which defines the joints as mirroring). But it's not so important for adding the Baxter in general. I would say this is good to merge :)

urdf2graspit has to be adjusted in order to make these future changes, there's something I still need to test, and my time is very limited right now (sorry for being so slow lately).... As soon as I can, I will work on this and then we can adjust the baxter.xml/eigen.xml, based on this version, in a separate PR.

Cheers
Jenny

**Comment by JSR694** [comment]
That all sounds good to me.  Are you also still planning on implementing the low-poly/primitives-based model?  Or should I take the lead on that?

**Comment by JenniferBuehler** [comment]
I wish I had the time to do that now, but it won't be possible any time soon, so if you take the lead on that, it would be awesome :)

**Pull request merged**
