### PR TITLE
To Eigen

### PR DESCRIPTION
**Pull request by jvarley**
Changes:
- convert vec3, mat3, quaternion, position to eigen equivalents
- flipped the order of transform multiplication in order to match what I believe is more commonly taught
- added eigen dependency to CMakeLists.txt
- extracted transf into transform.h/.cpp

Tested:
- dynamics + autograsp on plannerMug world with Grasit dynamics and Bullet Dynamics
- EGPlanner
- Planner
- AutoGrasp

These changes have made the EGPlanner ~6% faster, and I hope makes the code base more intuitive.

### CODE REVIEW

**Comment by jvarley** [comment]
@mateiciocarlie 
When you have sometime could you lend your thoughts on this.  

My thinking is we make a graspit 3.0 tag excluding this commit, and then pull this in.  It is a rather invasive chance but I think it makes working with transforms, poses, and quaternions significantly simpler in graspit.

**Comment by mateiciocarlie** [comment]
This looks like an excellent idea, and a big step forward. However, given the size, it (greatly) exceeds by bandwidth to look at in detail and vet :)

@jvarley - are there any downsides you can think of for moving to Eigen? How is availability under Windows? Ease of installation? Anything else?

**Comment by jvarley** [comment]
@mateiciocarlie 

Eigen is incredibly easy to install, it is one additional call to apt-get install.  This should be no more difficult than installing the other dependencies on Windows.  I can think of no downsides.  

I am going to do the following.
1) make a new tag for graspit 3.0 w/o this PR
2) pull this in to master.
3) update the docs to include eigen as a dependency.

**Comment by mateiciocarlie** [comment]
Sounds good to me! 

So, I take it that with Eigen in we're already looking at 4.0?

**Comment by jvarley** [comment]
Yup

**Pull request merged**
