### PR TITLE
Fixing issue #62: bad_alloc when setting DOF vals.

### PR DESCRIPTION
**Pull request by JSR694**
See issue 62.

### CODE REVIEW

**Comment by jvarley** [comment]
Looks preferable to a mysterious segfault to me.  I would change : 

Infinite time needed to set DOF (possibly due to value of desired DOF velocity)
to:
Infinite time needed to set DOF (due to dofVec[d]->getDesiredVelocity() returning 0)

Also, check your indentation.  Qtcreator always screws with it a bit.  Open it in emacs or something else.

**Comment by JSR694** [comment]
@jvarley what indentation+styling conventions are you using for Graspit?  I just added rules for [the ROS style guide](http://wiki.ros.org/CppStyleGuide)to my autoformatter, but it makes much more significant changes than what's present in this PR.

**Comment by jvarley** [comment]
The indentation is slightly off.  I have this problem when I use QtCreator as an ide.  Look at line 1919 and lines 1930-1934 of robot.cpp.  But open it up in github or with emacs rather than qtcreator.  It just needs to be tabbed in a bit more.  These lines are inside a for loop but in line with the for statement.  Its not a huge deal, I would just rather it was fixed before it was pulled in. 

What autoformatter do you use?

**Comment by JSR694** [comment]
I'll fix those tabs.  I use clang-format (via vim-clang-format), with the settings given in this config.  I believe ROS' style is a derivative of Google's, but I don't know the specific changes.

**Comment by jvarley** [comment]
Sorry, one last thing.  Why the extra set of << at the beginning of line 1919?

**Comment by JSR694** [comment]
My bad, I was in a rush and didn't try compiling.  Third time's a charm...

**Comment by jvarley** [comment]
have you tested it?

**Comment by JSR694** [comment]
Yes-- gc.setRobotDesiredDOF([0.39],[0]) on a 1-DOF hand produces the 
warning message.

**Pull request merged**
