### PR TITLE
fixed includes in QPSolver code that didn't reflect the changes made in pull request #120

### PR DESCRIPTION
**Pull request by mkghaas**

### CODE REVIEW

**Comment by jvarley** [comment]
LGTM

**Comment by jvarley** [comment]
Can we move all of these headers out of 
```
graspit/src/math/*.h
```
and into
```
graspit/include/graspit/math/*.h
```
In order to be consistent with the rest of GraspIt!. Headers from src are not copied to the install path, so it would not be possible to utilize these headers from a plugin that gets its headers from /usr/local/include/graspit

**Comment by mkghaas** [comment]
On it. I wasn't sure why the headers were in the source directory to begin with but thought there must be a reason so never changed it

**Comment by jvarley** [comment]
Yeah, they used to be all over the place.

**Pull request merged**
