### PR TITLE
Tactile

### PR DESCRIPTION
**Pull request by jvarley**
This is not ready to be pulled in.  I thought I would put this here so others can see it/contribute. I did not write most of it.

### CODE REVIEW

**Comment by jvarley** [comment]
@mateiciocarlie 
@jon-weisz 

This is ready to be talked about so that it can be pulled in.  

I made this the smallest PR possible.  I also removed the robot files with tactile sensors in order shrink the size of the  pr.  I will add a pr with the barrett with tactile sensors seperately. 

You can find a robot file with tactile sensors here:
https://github.com/jvarley/graspit/tree/tactile_current/models/robots/BarrettBH8_280_Tactile

This PR enables the use of filtered sensors.  They are modeled as 3d rectangles that are overlaid on the surface of the hand.  If a contact between the hand and the object occurs within the rectangle, then that sensor lights up.  In static mode, an elipsoid is fit to the contact and the nearby sensors also light up proportional to their distance from the contact location.

Current issues that I am not exactly thrilled with:
- sensors are owned by the world
- when sensors are polled the values are returned as a string

I am going to work on those this week, but I would like some feedback on this soon as well so we can merge it in.

-Jake

**Comment by mateiciocarlie** [comment]
Yup, this is a big one... It's made harder by the fact that there are a lot of "cosmetic changes" which obscure the real changes. I guess that' one reason people use strict formatting guides... Any chance you can take a look and try to get rid of some of the cosmetic changes?

What is the main reason that the sensors are owned by the world? I agree with you that it does not seem right.

**Comment by jvarley** [comment]
Alright, I removed all the spurious changes related to formatting.  

I am not aware of any reason why this was written with the world owning the sensors. I think I will just change ownership to the hand unless you have a different idea.

Also,  there have been a reasonable number of changes to the soft contact class.  Is this ok with you or do you think it would be better to make a new contact class called sensor contact and leave the original soft contact class intact?  I don't know much about the original soft contact class, so I am having a hard time determining if these are improvements or complete changes needing to exist in their own class.

**Comment by jvarley** [comment]
I moved the sensors to the robot from the world.  It was easier than I thought it would be.

**Comment by jvarley** [comment]
Also changed output of sensor readings to return a vec of the sensor readings rather than a qtextstream which had to be reparsed later on.

**Comment by mateiciocarlie** [comment]
Thanks for all the improvements! I'll take a look as soon as I have a bit of time, maybe tomorrow.

**Comment by mateiciocarlie** [comment]
This is now much much easier to parse, but that does highlight some issues...

The additions in here do not adhere to the style conventions. Member variables are not marked (lowercase m before the name in the rest of the codebase). There is no doxygen-style documentation - in the rest of the codebase (as much as we could) all variables and functions are documented, and classes have fairly extensive design explanations in the documentation. The new classes here have none of that. That makes it very hard to understand various issues, including why we need a new type of Link, what are the new variables added to the Contact class, what are the changes made to the soft contact fitting, etc. Changes to the Link hierarchy or the Contact class are fundamental enough that they should be well documented, and we should be sure of the necessity. 

This is change goes deep enough that I would really like the style and documentation to be there, which will also make it a lot easier to understand what is going on.

**Pull request merged**
