### PR TITLE
adding new arg parser

### PR DESCRIPTION
**Pull request by jvarley**
adding new arg parser, useful help message, and makes all arguments handled in a uniform way.
Functionality for loading hand, obstacle, object is the same, just more clear, changes way in which plugins are loaded in order to have uniform argument format. Also --help now provides useful message for how to pass in args.

### CODE REVIEW

**Comment by mateiciocarlie** [comment]
I am reluctant to add more third-party code into Graspit. Especially with such a vague license clause: "License: your favourite BSD-style license"

An alternative could be boost parsing.

**Comment by jvarley** [comment]
What if I got the author of that library to specify to license for the code?  If not, I agree, boost program options would be a reasonable alternative, although that would mean that boost would be a requirement for graspit to run.  If you are ok with that, then I can switch it over.  

http://www.boost.org/doc/libs/1_59_0/doc/html/program_options/tutorial.html

**Comment by mateiciocarlie** [comment]
You are right, not sure this is a good enough reason to bring in such a big dependency as Boost.

If the authors is willing to put in a proper BSD header in all files that should be good enough...

Also, please remove "using namespace optparse", especially from header files.

**Comment by jvarley** [comment]
Switched to a different library that has a better defined license.

**Comment by mateiciocarlie** [comment]
See note below in new license:

"Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution."

Please add the license of cmdline in our hyperlatex manual, in the section where we mention 3rd party software...

**Comment by jvarley** [comment]
Done.

**Pull request merged**
