### PR TITLE
Refactored src

### PR DESCRIPTION
**Pull request by jvarley**
Problem:
src contained many headers and ui elements for smaller subprojects

Fix:
move all ui files to ui/ 
move all .h to include/
make relevant fixes to CMakeLists.txt

Also:
removed a spurious .pro file and CVS entries

### CODE REVIEW

**Comment by jvarley** [comment]
@JenniferBuehler 
Do you have any thoughts on this.  I currently can't stand how ui and headers are kind of all over the place.

**Comment by JenniferBuehler** [comment]
Yes totally agree, I noticed that before, also that sometimes header files are in the src (sub)directories. I'd suggest the same as you, consistently across all folders:

- all ui files in "ui"
- all headers in "include"
- all cpp files in "src"

Nice and simple.

**Comment by jvarley** [comment]
@mateiciocarlie  this is ready as well.

**Comment by mateiciocarlie** [comment]
Would you guys mind if we sit on this for another 10 days or so?

We're in a big push for WAFR and have some changes in a branch - I'd like to merge in from master before this big change, but we're a bit tight on time this week...

Same goes for other much-needed but all-affecting changes like spacing and formatting.

**Comment by jvarley** [comment]
sure.

**Comment by JenniferBuehler** [comment]
no worries

**Pull request merged**
